/* Generated from 'wasm2kotlin.kt.tmpl' by wasm2c_tmpl.py, do not edit! */
const char SECTION_NAME(includes)[] =
"/* Automically generated by wasm2kotlin */\n"
"\n"
"import wasm_rt_impl.btoInt\n"
"import wasm_rt_impl.btoLong\n"
;
