set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER mips64el-linux-gnuabi64-gcc)
set(CMAKE_CXX_COMPILER mips64el-linux-gnuabi64-g++)

set(CMAKE_FIND_ROOT_PATH /usr/mips64el-linux-gnuabi64)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
